<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGhxT0YC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGhxT0YC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGhxT0YC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGhxT0YC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGhxT0YC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GhxT0YC',
    'container.build_id' => '154d6d7b',
    'container.build_time' => 1550941010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGhxT0YC');
