<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIR3WJnj\srcBRMControl_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIR3WJnj/srcBRMControl_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIR3WJnj.legacy');

    return;
}

if (!\class_exists(srcBRMControl_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIR3WJnj\srcBRMControl_KernelDevDebugContainer::class, srcBRMControl_KernelDevDebugContainer::class, false);
}

return new \ContainerIR3WJnj\srcBRMControl_KernelDevDebugContainer([
    'container.build_hash' => 'IR3WJnj',
    'container.build_id' => '1023467a',
    'container.build_time' => 1551530491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIR3WJnj');
