<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BRMControl\Command\DeleteRemoteCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/AbstractCommand.php';
include_once $this->targetDirs[3].'/src/Command/Traits/QuestionChooseRemote.php';
include_once $this->targetDirs[3].'/src/Command/DeleteRemoteCommand.php';

$this->privates['BRMControl\Command\DeleteRemoteCommand'] = $instance = new \BRMControl\Command\DeleteRemoteCommand(($this->privates['BRMControl\Service\DeviceReader'] ?? $this->load('getDeviceReaderService.php')), ($this->privates['BRMControl\Service\DeviceWriter'] ?? $this->load('getDeviceWriterService.php')));

$instance->setName('rmproplus:remote:delete');

return $instance;
