<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BRMControl\Service\DeviceReader' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/AbstractDeviceStorage.php';
include_once $this->targetDirs[3].'/src/Service/DeviceReader.php';
include_once $this->targetDirs[3].'/src/Service/DeviceSerializer.php';
include_once $this->targetDirs[3].'/src/Factory/RMPPlusFactory.php';

return $this->privates['BRMControl\Service\DeviceReader'] = new \BRMControl\Service\DeviceReader(($this->privates['BRMControl\Service\DeviceSerializer'] ?? ($this->privates['BRMControl\Service\DeviceSerializer'] = new \BRMControl\Service\DeviceSerializer())), ($this->privates['BRMControl\Factory\RMPPlusFactory'] ?? ($this->privates['BRMControl\Factory\RMPPlusFactory'] = new \BRMControl\Factory\RMPPlusFactory())), ($this->targetDirs[3].'/device/'), 'rmp_');
