<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BRMControl\Command\PlayScenarioCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/AbstractCommand.php';
include_once $this->targetDirs[3].'/src/Command/Traits/SaveDeviceTrait.php';
include_once $this->targetDirs[3].'/src/Command/Traits/QuestionChooseScenario.php';
include_once $this->targetDirs[3].'/src/Command/PlayScenarioCommand.php';
include_once $this->targetDirs[3].'/src/Service/ScenarioPlayer.php';
include_once $this->targetDirs[3].'/src/Service/CommandProvider.php';
include_once $this->targetDirs[3].'/src/Service/CommandCodeEncoder.php';

$this->privates['BRMControl\Command\PlayScenarioCommand'] = $instance = new \BRMControl\Command\PlayScenarioCommand(($this->privates['BRMControl\Service\DeviceReader'] ?? $this->load('getDeviceReaderService.php')), new \BRMControl\Service\ScenarioPlayer(($this->privates['BRMControl\Service\DeviceApiClient'] ?? $this->load('getDeviceApiClientService.php')), new \BRMControl\Service\CommandProvider(), ($this->privates['BRMControl\Service\CommandCodeEncoder'] ?? ($this->privates['BRMControl\Service\CommandCodeEncoder'] = new \BRMControl\Service\CommandCodeEncoder()))));

$instance->setName('rmproplus:scenario:play');

return $instance;
