<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'BRMControl\Controller\WidgetController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/WidgetController.php';

$this->services['BRMControl\Controller\WidgetController'] = $instance = new \BRMControl\Controller\WidgetController(($this->privates['BRMControl\Service\DeviceReader'] ?? $this->load('getDeviceReaderService.php')));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('BRMControl\\Controller\\WidgetController', $this));

return $instance;
