<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT9AHI3t\srcBRMControl_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT9AHI3t/srcBRMControl_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerT9AHI3t.legacy');

    return;
}

if (!\class_exists(srcBRMControl_KernelProdContainer::class, false)) {
    \class_alias(\ContainerT9AHI3t\srcBRMControl_KernelProdContainer::class, srcBRMControl_KernelProdContainer::class, false);
}

return new \ContainerT9AHI3t\srcBRMControl_KernelProdContainer([
    'container.build_hash' => 'T9AHI3t',
    'container.build_id' => '5419b06b',
    'container.build_time' => 1551481712,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT9AHI3t');
