<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFCR4YKX\srcBRMControl_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFCR4YKX/srcBRMControl_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerFCR4YKX.legacy');

    return;
}

if (!\class_exists(srcBRMControl_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerFCR4YKX\srcBRMControl_KernelProdDebugContainer::class, srcBRMControl_KernelProdDebugContainer::class, false);
}

return new \ContainerFCR4YKX\srcBRMControl_KernelProdDebugContainer([
    'container.build_hash' => 'FCR4YKX',
    'container.build_id' => 'b5e903b5',
    'container.build_time' => 1551481082,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFCR4YKX');
