<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BRMControl\Command\AddDeviceCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/AbstractCommand.php';
include_once $this->targetDirs[3].'/src/Command/AddDeviceCommand.php';
include_once $this->targetDirs[3].'/src/Factory/RMPPlusFactory.php';

$this->privates['BRMControl\Command\AddDeviceCommand'] = $instance = new \BRMControl\Command\AddDeviceCommand(($this->privates['BRMControl\Factory\RMPPlusFactory'] ?? ($this->privates['BRMControl\Factory\RMPPlusFactory'] = new \BRMControl\Factory\RMPPlusFactory())), ($this->privates['BRMControl\Service\DeviceWriter'] ?? $this->load('getDeviceWriterService.php')));

$instance->setName('rmproplus:device:add');

return $instance;
