<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BRMControl\Service\DeviceWriter' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/AbstractDeviceStorage.php';
include_once $this->targetDirs[3].'/src/Service/DeviceWriter.php';
include_once $this->targetDirs[3].'/src/Service/DeviceSerializer.php';

return $this->privates['BRMControl\Service\DeviceWriter'] = new \BRMControl\Service\DeviceWriter(($this->privates['BRMControl\Service\DeviceSerializer'] ?? ($this->privates['BRMControl\Service\DeviceSerializer'] = new \BRMControl\Service\DeviceSerializer())), ($this->targetDirs[3].'/device/'), 'rmp_');
